<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "beer"
 *
 * Auto generated by Extension Builder 2014-12-17
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'MOC Extbase beer',
	'description' => 'Demo extension for educational puposes',
	'category' => 'plugin',
	'author' => 'Jan-Erik Revsbech, View beers',
	'author_email' => 'janerik@moc.net',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);